### PR TITLE
added the classes for the taskbar buttons

### PR DESCRIPTION
**Pull request by noahjeans**
Added taskbar activity classes
- each linked to their xml file

### CODE REVIEW

**Review by tjpollom — CHANGES_REQUESTED** [review]
I don't believe these classes should extend MainActivity. It should be, as far as I know, AppCompatActivity.

These classes must have documentation in the Javadoc style, which at this point should only mention which UI element they are linked to; for instance, Account should mention that it is linked to the account_screen XML and handles showing / dealing with Account Details. Importantly, please include in this comment if the Taskbar needs to work with this class.

The on-click listeners in Main are linked manually; later (not right now) those will have to be re-written to use the Taskbar object.

**Comment by noahjeans** [comment]
just finished changing the things you asked. I think it should be all good but I am unsure if I updated the manifest properly so please lemme know.

**Review by tjpollom — APPROVED** [review]
This looks good; the only concern I have is that there should also be activities for every single new screen and I'm not sure offhand if this is all of them.

**Review by anjelica-m — APPROVED** [review]
Changes look good! The only other screens I can think we possibly might need (based on our interface mockup, which we may need to revisit) are the PlayerAccountSearch, CodeSearch, and LoginScreen or a CreateAccount page for the first time the app is run on the device. However we may decide to do player and code search as pop ups, but that can be left for part 4 as I don't believe it's one of our main goals for this part.

**Comment by tjpollom** [comment]
The manifests file was broken and not allowing switching between activities (it would crash upon attempting to do so). Thankfully, @anjelica-m figured out a fix to the file that now lets it work as expected.

**Pull request merged**
